//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsnPasswordFinder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MsnPasswordFinder.LangRes", typeof(LangRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list has more than one record. You may not want to see&apos;em all. If you think like this press Yes and you can only see selected account&apos;s password..
        /// </summary>
        internal static string EN_Attention {
            get {
                return ResourceManager.GetString("EN_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string EN_Copy {
            get {
                return ResourceManager.GetString("EN_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy&apos;em All.
        /// </summary>
        internal static string EN_CopyAll {
            get {
                return ResourceManager.GetString("EN_CopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading cred info..
        /// </summary>
        internal static string EN_Error {
            get {
                return ResourceManager.GetString("EN_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Id.
        /// </summary>
        internal static string EN_LiveIdColumn {
            get {
                return ResourceManager.GetString("EN_LiveIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string EN_Ok {
            get {
                return ResourceManager.GetString("EN_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string EN_PasswordColumn {
            get {
                return ResourceManager.GetString("EN_PasswordColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD NOT SET.
        /// </summary>
        internal static string EN_PwdNotSet {
            get {
                return ResourceManager.GetString("EN_PwdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item first..
        /// </summary>
        internal static string EN_SelectItemWarn {
            get {
                return ResourceManager.GetString("EN_SelectItemWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Live Messenger Stored Password Recovery.
        /// </summary>
        internal static string EN_Title {
            get {
                return ResourceManager.GetString("EN_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listede birden fazla kayıt var. Belki hepsini görmek istemeyebilirsiniz. Eğer öyle düşünüyorsanız Evet&apos;i tıklayıp seçtiğiniz hesaba ait parolayı görebilirsiniz..
        /// </summary>
        internal static string TR_Attention {
            get {
                return ResourceManager.GetString("TR_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopyala.
        /// </summary>
        internal static string TR_Copy {
            get {
                return ResourceManager.GetString("TR_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hepsini Kopyala.
        /// </summary>
        internal static string TR_CopyAll {
            get {
                return ResourceManager.GetString("TR_CopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cred bilgilerini okurken bir hata oluştu..
        /// </summary>
        internal static string TR_Error {
            get {
                return ResourceManager.GetString("TR_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Kimliği.
        /// </summary>
        internal static string TR_LiveIdColumn {
            get {
                return ResourceManager.GetString("TR_LiveIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        internal static string TR_Ok {
            get {
                return ResourceManager.GetString("TR_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        internal static string TR_PasswordColumn {
            get {
                return ResourceManager.GetString("TR_PasswordColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAROLA ATANMAMIŞ.
        /// </summary>
        internal static string TR_PwdNotSet {
            get {
                return ResourceManager.GetString("TR_PwdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen önce bir eleman seçin..
        /// </summary>
        internal static string TR_SelectItemWarn {
            get {
                return ResourceManager.GetString("TR_SelectItemWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Live Messenger Kayıtlı Parola Kurtarıcısı.
        /// </summary>
        internal static string TR_Title {
            get {
                return ResourceManager.GetString("TR_Title", resourceCulture);
            }
        }
    }
}
